# Generated by Django 5.0.14 on 2025-08-06 17:31

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Client',
                'db_table': 'Client',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'LU Identification',
                'db_table': 'LU_Identification',
            },
        ),
        migrations.CreateModel(
            name='ITEMCHANGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=100)),
                ('new_value', models.CharField(max_length=100)),
                ('change_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ITEM CHANGES',
                'verbose_name_plural': 'ITEM CHANGES',
                'db_table': 'ITEM_CHANGES',
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('dollar_amount', models.FloatField(max_length=20)),
            ],
            options={
                'verbose_name': 'Premium',
                'db_table': 'Premium',
            },
        ),
        migrations.CreateModel(
            name='PremiumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'LU Premium',
                'db_table': 'LU_Premium',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'LU Status',
                'verbose_name_plural': 'LU Statuses',
                'db_table': 'LU_Status',
            },
        ),
        migrations.CreateModel(
            name='ClientIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('Client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client')),
            ],
            options={
                'verbose_name': 'Client Identification',
                'db_table': 'Client_Identification',
            },
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_name_case_insensitive_unique', violation_error_message='Genre already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='clientidentification',
            name='LU_Identification_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.identificationtype'),
        ),
        migrations.AddField(
            model_name='itemchanges',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premium',
            name='LU_Premium_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.premiumtype'),
        ),
        migrations.AddField(
            model_name='premium',
            name='LU_Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.statustype'),
        ),
        migrations.AddField(
            model_name='clientidentification',
            name='LU_Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.statustype'),
        ),
    ]
