# Generated by Django 4.2.23 on 2025-08-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('dollar_amount', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Identification Type',
                'db_table': 'LU_Identification',
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Status Type',
                'verbose_name_plural': 'Status Types',
                'db_table': 'LU_Status',
            },
        ),
        migrations.CreateModel(
            name='ITEMCHANGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=100)),
                ('new_value', models.CharField(max_length=100)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ITEM CHANGES',
                'verbose_name_plural': 'ITEM CHANGES',
                'db_table': 'ITEM_CHANGES',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('unit', models.IntegerField()),
                ('optional', models.CharField(max_length=200)),
                ('client_premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.clientpremium')),
            ],
            options={
                'verbose_name': 'Invoices',
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoices',
            },
        ),
        migrations.AddField(
            model_name='clientpremium',
            name='LU_Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.statustype'),
        ),
        migrations.AddField(
            model_name='clientpremium',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.client'),
        ),
        migrations.AddField(
            model_name='clientpremium',
            name='premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.premium'),
        ),
        migrations.CreateModel(
            name='ClientIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('Client_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.client')),
                ('LU_Identification_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.identificationtype', verbose_name='Identification Name')),
                ('LU_Status_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.statustype', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Client Identification',
                'db_table': 'Client_Identification',
            },
        ),
    ]
