# Generated by Django 4.2.23 on 2025-08-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='Client_ID',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='invoice.client'),
        ),
    ]
