# Generated by Django 4.2.23 on 2025-09-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_duedatetype_historicalinvoice_duedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='duedate',
        ),
    ]
