# Generated by Django 4.2.23 on 2025-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_premium_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientidentification',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
