# Generated by Django 4.2.23 on 2025-08-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_clientidentification_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premium',
            options={'verbose_name': 'Client Premium'},
        ),
        migrations.AlterModelTable(
            name='premium',
            table='Client_Premium',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('optional', models.CharField(max_length=200)),
                ('Premium_ID', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='invoice.premium')),
            ],
            options={
                'verbose_name': 'Invoice',
                'db_table': 'Invoice',
            },
        ),
    ]
