# Generated by Django 4.2.23 on 2025-09-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_historicalinvoice_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='duedate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoice.duedatetype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='duedate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.duedatetype'),
            preserve_default=False,
        ),
    ]
