# Generated by Django 4.2.23 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_historicalinvoice_duedate_invoice_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='optional',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='optional',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
