# Generated by Django 4.2.23 on 2025-08-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_premium_options_alter_premium_table_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificationtype',
            options={'verbose_name': 'Identification Type'},
        ),
        migrations.AlterModelOptions(
            name='premiumtype',
            options={'verbose_name': 'Premium Type'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name': 'Status Type', 'verbose_name_plural': 'Status Types'},
        ),
        migrations.AlterField(
            model_name='clientidentification',
            name='Client_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='clientidentification',
            name='LU_Identification_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.identificationtype', verbose_name='Identification Name'),
        ),
        migrations.AlterField(
            model_name='clientidentification',
            name='LU_Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.statustype', verbose_name='Status'),
        ),
    ]
