# Generated by Django 4.2.23 on 2025-08-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_identificationtype_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='Invoices',
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name': 'Invoices'},
        ),
        migrations.AlterModelTable(
            name='invoices',
            table='Invoices',
        ),
    ]
