# Generated by Django 4.2.23 on 2025-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_historicalinvoice_optional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='optional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='optional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
