# Generated by Django 4.2.23 on 2025-08-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0007_rename_invoice_invoices_alter_invoices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientidentification',
            name='Client_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='clientidentification',
            name='LU_Identification_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.identificationtype', verbose_name='Identification Name'),
        ),
        migrations.AlterField(
            model_name='clientidentification',
            name='LU_Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.statustype', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='Premium_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.premium'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemchanges',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='premium',
            name='Client_ID',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='invoice.client'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='LU_Premium_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.premiumtype'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='LU_Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.statustype'),
        ),
    ]
