# Generated by Django 4.2.23 on 2025-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_historicalinvoice_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
