# Generated by Django 4.2.23 on 2025-10-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_historicalinvoice_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
