# Generated by Django 4.2.23 on 2025-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_historicalinvoice_paid_amount_invoice_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
