# Generated by Django 4.2.23 on 2025-10-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_historicalinvoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.clientpremium'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='duedate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.duedatetype'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
                'db_table': 'Payments',
            },
        ),
    ]
