# Generated by Django 4.2.23 on 2025-10-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_historicalinvoice_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.AlterField(
            model_name='payments',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoice.invoice'),
        ),
    ]
